modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
#issueTrackerURL = ""
license = "MIT Licensed"

[[mods]]
modId = "emixx"
version = "${version}"
displayName = "EMI++"
authors = "ConcerroX"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[mixins]]
config = "emixx.mixins.json"

[[mixins]]
config = "emixx-common.mixins.json"

[[dependencies.emixx]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emixx]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"
